bookmark/urls.py
from django.urls import path
from . import views

# 템플릿엥서 app name을 바로바로 url 타고 가기 쉽게 하기 위해서
# app 이 여러개 일 떄
app_name = "bookmark"

urlpatterns = [
    path('', views.list, name="list"),
    path('<int:pk>/', views.cate_detail, name="cate_detail"),
    path('cate_new/', views.cate_new, name='cate_new'),
    path('<int:pk>/cafe_edit/', views.cate_edit, name='cate_edit'),
    path('<int:pk>/cate_delete/', views.cate_delete, name='cate_delete'),
    path('mark_new/', views.mark_new, name='mark_new'),
    path('<int:pk>/mark_edit/', views.mark_edit, name='mark_edit'),
    path('<int:pk>/mark_delete/', views.mark_delete, name='mark_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookmark.urls')),
]

bookmark/models.py
from unicodedata import category
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=10)
    desc = models.CharField(max_length=100)

    def __str__(self):
        return "[" + self.name + "]" + self.desc
    # str 함수를 정의하지 않으면 catetory(1) 과 같이 안 예쁘게 뜬다
# str 함수 추가하는 건 테이블을 바꾸는 게 아니므로 migrate 필요 x


class Mark(models.Model):
    name = models.CharField(max_length=20)
    url = models.URLField("Site URL")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return "["+self.category.name+"]" + self.name+" : " + self.url
    # 외래키에선 category에서 어떤 걸 가져올지 명시해줘야 함.

bookmark/forms.py
from django import forms
from .models import Mark, Category

class MarkForm(forms.ModelForm):
    class Meta:
        model = Mark
        fields = ('__all__')

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('__all__')

bookmark/views.py
from django.shortcuts import render, get_object_or_404, redirect
from bookmark.forms import CategoryForm, MarkForm

from bookmark.models import Category, Mark

# Create your views here.


def list(request):
    cates = Category.objects.all()
    order_marks = {}
    for c in cates:
        marks = Mark.objects.filter(category=c)
        order_marks[c] = marks
    # 해당 카테고리에 해당하는 마크들을 가지고 있는 딕셔너리가 만들어진다
    ctx = {
        'order_marks': order_marks
    }
    return render(request, 'bookmark/list.html', context=ctx)

def cate_detail(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    marks = cate.mark_set.all()
    # _set 으로 외래키로 연결되어 있는 오브젝트들을 가져올 수 있다
    # cate 에 연결되어 있는 marks 오브젝트들을 다 가져온다.
    ctx = {
        'cate': cate,
        'marks':marks,
    }
    return render(request, 'bookmark/cate_detail.html', context=ctx)

def cate_new(request):
    if request.method =="POST":
        form =CategoryForm(request.POST)
        if form.is_valid():
            cate = form.save()
            return redirect('bookmark:cate_detail', pk=cate.pk)
    else:
        form =CategoryForm()
    ctx = {
        'form': form,
    }
    return render(request, 'bookmark/form.html', context=ctx)

def cate_edit(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    if request.method =="POST":
        form =CategoryForm(request.POST, instance=cate)
        if form.is_valid():
            cate = form.save()
            return redirect('bookmark:cate_detail', pk=cate.pk)
    else:
        form =CategoryForm(instance=cate)
    ctx = {
        'form': form,
    }
    return render(request, 'bookmark/form.html', context=ctx)

def cate_delete(request,pk):
    cate = get_object_or_404(Category, pk=pk)
    cate.delete()
    return redirect('bookmark:list')

def mark_new(request):
    if request.method == "POST":
        form = MarkForm(request.POST)
        if form.is_valid():
            mark = form.save()
            cate = mark.category
            return redirect('bookmark:cate_detail', pk=cate.pk)
    else:
        form = MarkForm()
    ctx = {
        'form': form
    }
    return render(request, 'bookmark/form.html', context=ctx)

def mark_edit(request, pk):
    mark = get_object_or_404(Mark, pk=pk)
    if request.method =="POST":
        form = MarkForm(request.POST, instance=mark)
        if form.is_valid():
            mark = form.save()
            cate = mark.category
            return redirect('bookmark:cate_detail', pk=cate.pk)
    else:
        form =MarkForm(instance=mark)
    ctx = {
        'form': form
    }
    return render(request, 'bookmark/form.html', context=ctx)

def mark_delete(request,pk):
    mark = get_object_or_404(Mark, pk=pk)
    mark.delete()
    return redirect('bookmark:list')

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {% endblock %}</title>
    <!-- 페이지마다 타이틀 다르게 하기 위해 block title -->
  </head>
  <body>
    <a href="{% url 'bookmark:list' %}">메인으로</a>
    <a href="{% url 'bookmark:cate_new' %}">카테고리 추가</a>
    <a href="{% url 'bookmark:mark_new' %}">북마크 추가</a>
    {% block content %} {% endblock %}
  </body>
</html>

templates/bookmark/cate_detail.html
{% extends 'base.html' %}

{% block title %} Category {% endblock %}

{% block content %}

<h3> {{cate.name}} </h3>
<a href="{% url 'bookmark:cate_edit' pk=cate.pk %}">수정</a>
<a href="{% url 'bookmark:cate_delete' pk=cate.pk%}">삭제</a>
<p> {{cate.desc}} </p>

<ul>
    {% for m in marks %}
        <li>
            <a href="{{ m.url }}"> {{m.name}} </a>
            <a href="{% url 'bookmark:mark_edit' pk=m.pk %}">수정</a>
            <a href="{% url 'bookmark:mark_delete' pk=m.pk%}">삭제</a>
        </li>

    {% endfor %}
</ul>

{% endblock%}

templates/bookmark/form.html
{% extends 'base.html' %}
{% block title %}Create{% endblock %}

{% block content %}
    <h4>Create</h4>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">저장</button>
    </form>


{% endblock %}

templates/bookmark/list.html
{% extends 'base.html' %}
{% block title %}Bookmark{% endblock %}
{% block content %}

{% for cate, marks in order_marks.items %}
    <h3><a href="{% url 'bookmark:cate_detail' pk=cate.pk %}">{{ cate.name }}</a></h3>
    <ul>
        {% for m in marks %}
            <li>
                <a href="{{ m.url }}">{{ m.name }}</a>
            </li>
        {% endfor %}
    </ul>

{% endfor %}

{% endblock %}